
#ifndef X
# define X(ret, name, args)
#endif

#ifndef __linux__
X(void, glActiveTexture, (GLenum texture))
X(void, glBlendColor, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))
X(void, glBlendEquation, (GLenum mode))
X(void, glCompressedTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data))
X(void, glCompressedTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data))
X(void, glSampleCoverage, (GLfloat value, GLboolean invert))
X(void, glDrawRangeElements, (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices))
X(void, glTexImage3D, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels))
X(void, glTexSubImage3D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels))
X(void, glCopyTexSubImage3D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height))
X(void, glCompressedTexImage3D, (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data))
X(void, glCompressedTexSubImage3D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data))
#endif

X(void, glMultiDrawArrays, (GLenum mode, const GLint * first, const GLsizei * count, GLsizei drawcount))
X(void, glMultiDrawArraysIndirect, (GLenum mode, const void* indirect, GLsizei drawcount, GLsizei stride))
X(void, glDebugMessageCallback, (GLDEBUGPROC callback, const void *userParam))
X(void, glAttachShader, (GLuint program, GLuint shader))
X(void, glBindAttribLocation, (GLuint program, GLuint index, const GLchar *name))
X(void, glBindBuffer, (GLenum target, GLuint buffer))
X(void, glBindFramebuffer, (GLenum target, GLuint framebuffer))
X(void, glBindRenderbuffer, (GLenum target, GLuint renderbuffer))
X(void, glBlendEquationSeparate, (GLenum modeRGB, GLenum modeAlpha))
X(void, glBlendFuncSeparate, (GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha))
X(void, glBufferData, (GLenum target, GLsizeiptr size, const void *data, GLenum usage))
X(void, glBufferSubData, (GLenum target, GLintptr offset, GLsizeiptr size, const void *data))
X(GLenum, glCheckFramebufferStatus, (GLenum target))
X(void, glClearDepthf, (GLfloat d))
X(void, glCompileShader, (GLuint shader))
X(GLuint, glCreateProgram, (void))
X(GLuint, glCreateShader, (GLenum type))
X(void, glDeleteBuffers, (GLsizei n, const GLuint *buffers))
X(void, glDeleteFramebuffers, (GLsizei n, const GLuint *framebuffers))
X(void, glDeleteProgram, (GLuint program))
X(void, glDeleteRenderbuffers, (GLsizei n, const GLuint *renderbuffers))
X(void, glDeleteShader, (GLuint shader))
X(void, glDepthRangef, (GLfloat n, GLfloat f))
X(void, glDetachShader, (GLuint program, GLuint shader))
X(void, glDisableVertexAttribArray, (GLuint index))
X(void, glEnableVertexAttribArray, (GLuint index))
X(void, glFramebufferRenderbuffer, (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer))
X(void, glFramebufferTexture2D, (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level))
X(void, glGenBuffers, (GLsizei n, GLuint *buffers))
X(void, glGenerateMipmap, (GLenum target))
X(void, glGenFramebuffers, (GLsizei n, GLuint *framebuffers))
X(void, glGenRenderbuffers, (GLsizei n, GLuint *renderbuffers))
X(void, glGetActiveAttrib, (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name))
X(void, glGetActiveUniform, (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name))
X(void, glGetAttachedShaders, (GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders))
X(GLint, glGetAttribLocation, (GLuint program, const GLchar *name))
X(void, glGetBufferParameteriv, (GLenum target, GLenum pname, GLint *params))
X(void, glGetFramebufferAttachmentParameteriv, (GLenum target, GLenum attachment, GLenum pname, GLint *params))
X(void, glGetProgramiv, (GLuint program, GLenum pname, GLint *params))
X(void, glGetProgramInfoLog, (GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog))
X(void, glGetRenderbufferParameteriv, (GLenum target, GLenum pname, GLint *params))
X(void, glGetShaderiv, (GLuint shader, GLenum pname, GLint *params))
X(void, glGetShaderInfoLog, (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog))
X(void, glGetShaderPrecisionFormat, (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision))
X(void, glGetShaderSource, (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source))
X(void, glGetUniformfv, (GLuint program, GLint location, GLfloat *params))
X(void, glGetUniformiv, (GLuint program, GLint location, GLint *params))
X(GLint, glGetUniformLocation, (GLuint program, const GLchar *name))
X(void, glGetVertexAttribfv, (GLuint index, GLenum pname, GLfloat *params))
X(void, glGetVertexAttribiv, (GLuint index, GLenum pname, GLint *params))
X(void, glGetVertexAttribPointerv, (GLuint index, GLenum pname, void **pointer))
X(GLboolean, glIsBuffer, (GLuint buffer))
X(GLboolean, glIsFramebuffer, (GLuint framebuffer))
X(GLboolean, glIsProgram, (GLuint program))
X(GLboolean, glIsRenderbuffer, (GLuint renderbuffer))
X(GLboolean, glIsShader, (GLuint shader))
X(void, glLinkProgram, (GLuint program))
X(void, glReleaseShaderCompiler, (void))
X(void, glRenderbufferStorage, (GLenum target, GLenum internalformat, GLsizei width, GLsizei height))
X(void, glShaderBinary, (GLsizei count, const GLuint *shaders, GLenum binaryformat, const void *binary, GLsizei length))
X(void, glShaderSource, (GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length))
X(void, glStencilFuncSeparate, (GLenum face, GLenum func, GLint ref, GLuint mask))
X(void, glStencilMaskSeparate, (GLenum face, GLuint mask))
X(void, glStencilOpSeparate, (GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass))
X(void, glUniform1f, (GLint location, GLfloat v0))
X(void, glUniform1fv, (GLint location, GLsizei count, const GLfloat *value))
X(void, glUniform1i, (GLint location, GLint v0))
X(void, glUniform1iv, (GLint location, GLsizei count, const GLint *value))
X(void, glUniform2f, (GLint location, GLfloat v0, GLfloat v1))
X(void, glUniform2fv, (GLint location, GLsizei count, const GLfloat *value))
X(void, glUniform2i, (GLint location, GLint v0, GLint v1))
X(void, glUniform2iv, (GLint location, GLsizei count, const GLint *value))
X(void, glUniform3f, (GLint location, GLfloat v0, GLfloat v1, GLfloat v2))
X(void, glUniform3fv, (GLint location, GLsizei count, const GLfloat *value))
X(void, glUniform3i, (GLint location, GLint v0, GLint v1, GLint v2))
X(void, glUniform3iv, (GLint location, GLsizei count, const GLint *value))
X(void, glUniform4f, (GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3))
X(void, glUniform4fv, (GLint location, GLsizei count, const GLfloat *value))
X(void, glUniform4i, (GLint location, GLint v0, GLint v1, GLint v2, GLint v3))
X(void, glUniform4iv, (GLint location, GLsizei count, const GLint *value))
X(void, glUniformMatrix2fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
X(void, glUniformMatrix3fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
X(void, glUniformMatrix4fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
X(void, glUseProgram, (GLuint program))
X(void, glValidateProgram, (GLuint program))
X(void, glVertexAttrib1f, (GLuint index, GLfloat x))
X(void, glVertexAttrib1fv, (GLuint index, const GLfloat *v))
X(void, glVertexAttrib2f, (GLuint index, GLfloat x, GLfloat y))
X(void, glVertexAttrib2fv, (GLuint index, const GLfloat *v))
X(void, glVertexAttrib3f, (GLuint index, GLfloat x, GLfloat y, GLfloat z))
X(void, glVertexAttrib3fv, (GLuint index, const GLfloat *v))
X(void, glVertexAttrib4f, (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w))
X(void, glVertexAttrib4fv, (GLuint index, const GLfloat *v))
X(void, glVertexAttribPointer, (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer))
X(void, glGenQueries, (GLsizei n, GLuint *ids))
X(void, glDeleteQueries, (GLsizei n, const GLuint *ids))
X(GLboolean, glIsQuery, (GLuint id))
X(void, glBeginQuery, (GLenum target, GLuint id))
X(void, glEndQuery, (GLenum target))
X(void, glGetQueryiv, (GLenum target, GLenum pname, GLint *params))
X(void, glGetQueryObjectuiv, (GLuint id, GLenum pname, GLuint *params))
X(GLboolean, glUnmapBuffer, (GLenum target))
X(void, glGetBufferPointerv, (GLenum target, GLenum pname, void **params))
X(void, glDrawBuffers, (GLsizei n, const GLenum *bufs))
X(void, glUniformMatrix2x3fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
X(void, glUniformMatrix3x2fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
X(void, glUniformMatrix2x4fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
X(void, glUniformMatrix4x2fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
X(void, glUniformMatrix3x4fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
X(void, glUniformMatrix4x3fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
X(void, glBlitFramebuffer, (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter))
X(void, glRenderbufferStorageMultisample, (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height))
X(void, glFramebufferTextureLayer, (GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer))
X(void*, glMapBufferRange, (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access))
X(void, glFlushMappedBufferRange, (GLenum target, GLintptr offset, GLsizeiptr length))
X(void, glBindVertexArray, (GLuint array))
X(void, glDeleteVertexArrays, (GLsizei n, const GLuint *arrays))
X(void, glGenVertexArrays, (GLsizei n, GLuint *arrays))
X(GLboolean, glIsVertexArray, (GLuint array))
X(void, glGetIntegeri_v, (GLenum target, GLuint index, GLint *data))
X(void, glBeginTransformFeedback, (GLenum primitiveMode))
X(void, glEndTransformFeedback, (void))
X(void, glBindBufferRange, (GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size))
X(void, glBindBufferBase, (GLenum target, GLuint index, GLuint buffer))
X(void, glTransformFeedbackVaryings, (GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode))
X(void, glGetTransformFeedbackVarying, (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name))
X(void, glVertexAttribIPointer, (GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer))
X(void, glGetVertexAttribIiv, (GLuint index, GLenum pname, GLint *params))
X(void, glGetVertexAttribIuiv, (GLuint index, GLenum pname, GLuint *params))
X(void, glVertexAttribI4i, (GLuint index, GLint x, GLint y, GLint z, GLint w))
X(void, glVertexAttribI4ui, (GLuint index, GLuint x, GLuint y, GLuint z, GLuint w))
X(void, glVertexAttribI4iv, (GLuint index, const GLint *v))
X(void, glVertexAttribI4uiv, (GLuint index, const GLuint *v))
X(void, glGetUniformuiv, (GLuint program, GLint location, GLuint *params))
X(GLint, glGetFragDataLocation, (GLuint program, const GLchar *name))
X(void, glUniform1ui, (GLint location, GLuint v0))
X(void, glUniform2ui, (GLint location, GLuint v0, GLuint v1))
X(void, glUniform3ui, (GLint location, GLuint v0, GLuint v1, GLuint v2))
X(void, glUniform4ui, (GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3))
X(void, glUniform1uiv, (GLint location, GLsizei count, const GLuint *value))
X(void, glUniform2uiv, (GLint location, GLsizei count, const GLuint *value))
X(void, glUniform3uiv, (GLint location, GLsizei count, const GLuint *value))
X(void, glUniform4uiv, (GLint location, GLsizei count, const GLuint *value))
X(void, glClearBufferiv, (GLenum buffer, GLint drawbuffer, const GLint *value))
X(void, glClearBufferuiv, (GLenum buffer, GLint drawbuffer, const GLuint *value))
X(void, glClearBufferfv, (GLenum buffer, GLint drawbuffer, const GLfloat *value))
X(void, glClearBufferfi, (GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil))
X(const GLubyte*, glGetStringi, (GLenum name, GLuint index))
X(void, glCopyBufferSubData, (GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size))
X(void, glGetUniformIndices, (GLuint program, GLsizei uniformCount, const GLchar *const*uniformNames, GLuint *uniformIndices))
X(void, glGetActiveUniformsiv, (GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params))
X(GLuint, glGetUniformBlockIndex, (GLuint program, const GLchar *uniformBlockName))
X(void, glGetActiveUniformBlockiv, (GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params))
X(void, glGetActiveUniformBlockName, (GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName))
X(void, glUniformBlockBinding, (GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding))
X(void, glDrawArraysInstanced, (GLenum mode, GLint first, GLsizei count, GLsizei instancecount))
X(void, glDrawElementsInstanced, (GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount))
X(GLsync, glFenceSync, (GLenum condition, GLbitfield flags))
X(GLboolean, glIsSync, (GLsync sync))
X(void, glDeleteSync, (GLsync sync))
X(GLenum, glClientWaitSync, (GLsync sync, GLbitfield flags, GLuint64 timeout))
X(void, glWaitSync, (GLsync sync, GLbitfield flags, GLuint64 timeout))
X(void, glGetInteger64v, (GLenum pname, GLint64 *data))
X(void, glGetSynciv, (GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values))
X(void, glGetInteger64i_v, (GLenum target, GLuint index, GLint64 *data))
X(void, glGetBufferParameteri64v, (GLenum target, GLenum pname, GLint64 *params))
X(void, glGenSamplers, (GLsizei count, GLuint *samplers))
X(void, glDeleteSamplers, (GLsizei count, const GLuint *samplers))
X(GLboolean, glIsSampler, (GLuint sampler))
X(void, glBindSampler, (GLuint unit, GLuint sampler))
X(void, glSamplerParameteri, (GLuint sampler, GLenum pname, GLint param))
X(void, glSamplerParameteriv, (GLuint sampler, GLenum pname, const GLint *param))
X(void, glSamplerParameterf, (GLuint sampler, GLenum pname, GLfloat param))
X(void, glSamplerParameterfv, (GLuint sampler, GLenum pname, const GLfloat *param))
X(void, glGetSamplerParameteriv, (GLuint sampler, GLenum pname, GLint *params))
X(void, glGetSamplerParameterfv, (GLuint sampler, GLenum pname, GLfloat *params))
X(void, glVertexAttribDivisor, (GLuint index, GLuint divisor))
X(void, glBindTransformFeedback, (GLenum target, GLuint id))
X(void, glDeleteTransformFeedbacks, (GLsizei n, const GLuint *ids))
X(void, glGenTransformFeedbacks, (GLsizei n, GLuint *ids))
X(GLboolean, glIsTransformFeedback, (GLuint id))
X(void, glPauseTransformFeedback, (void))
X(void, glResumeTransformFeedback, (void))
X(void, glGetProgramBinary, (GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary))
X(void, glProgramBinary, (GLuint program, GLenum binaryFormat, const void *binary, GLsizei length))
X(void, glProgramParameteri, (GLuint program, GLenum pname, GLint value))
X(void, glInvalidateFramebuffer, (GLenum target, GLsizei numAttachments, const GLenum *attachments))
X(void, glInvalidateSubFramebuffer, (GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height))
X(void, glTexStorage2D, (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height))
X(void, glTexStorage3D, (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth))
X(void, glGetInternalformativ, (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint *params))
X(void, glGetBufferSubData, (GLenum target, GLintptr offset, GLsizeiptr size, void * data))

